### ISSUE TITLE
Walk submitter through submission checklist.

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/liq-cli#109]
## Overview

Any certifications which need to be made according to company policy will be incorporated into the `liq projects submit` command.

## Deliverables

* [x] The policy walkthrough should be encoded as part of the company policy, which is extracted from the 'policy' dependencies' under `$HOME/.liquid-development/orgs/curr_org/public/package.json`. 'type' is either 'code', 'network', 'policy', or 'data'. The type is defined in `package.json` under `.liquidDev.changeControl.type`. Each policy dep will be search for `~/policy/change-control/<type>/`, and any files matching `/submit-checks.tsv$/` will be used.
* [x] For each entry in the file (after the header), the user should be presented with the question with 'yes/no/cancel' options; no default and full "yes", "no", or "c" required.
* [x] If 'no', then user is given option to continue submission anyway with exceptions noted.
* [x] The previous exception explanation is saved and used as a default option for remaining exceptions.
* [x] For LL, we'll add the following as a test/bootstrap:
  * [x] "Has inline documentation been included with all newly added or significantly modified functions and/or tests?" unconditional
  * [x] "Have all new or modified functions dealing with access to sensitive material (user keys, passwords, etc.) been flagged as 'SENSITIVE' in the inline docs and inline at the head of the function or near the sensitive section of code?" with condition `SECURITY_ENV > SEC_TRIVIAL`
* [x] The results of the walkthrough are appended to the submit description.
