### ISSUE TITLE
Sketch in support for 'meta extensions install'.

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/liq-cli#174]
# Overview

It makes sense to break up the domain functionality into different modules that get combined as they are installed.

# Deliverables

* [x] On install, create `$HOME/.liquid-development/exts`.
* [x] Create new project for `liq-ext-data`
* [x] Migrate the `data` command group code to that do and add a root `inc.sh` file in src that pulls in the rest of the files (mostly indirectly of course follow he 'pull in files from same dir and incs from subdirs pattern).
* Implement `meta extensions install` command group.
   * [x] Creates `extensions` dir in `~/.liquid-development` is necessary.
   * [x] Change `liq` to dynamically source 
   * [x] Installs via npm by default, so we first implement `--local` which will look for the package in the local playground and `liq work link` the specified package (instead of `npm install`)
   * [x] With the `--local` option, if it is not locally installed, then imports the package first.
   * [x] Find the install location in `node_modules` and add a file with just package name (ignore org) with include. So, we can do something like: `for EXT in $(ls extensions); do source $EXT`
   * [x] Break out the 'data' specific completion bits.
* [x] implement non-local install which just installs npm package.

# Note

I believe even though we're not installing with NPM, we should still be able to leverage NPMs semantic version resolution to install compatible versions.
