### ISSUE TITLE
Implement 'meta next'

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/liq-cli#180]
# Overview

Let liq coach you. What's `meta next`?

# Deliverables

* [x] Implement `meta next` to do initial install check.
* [x] Otherwise, check for current work.
* If no current work:
   * [x] Check if in project dir and suggest `liq work start ...`
   * [x] If not in project dir, suggest `cd some/project/path`
* [x] Else if current work, suggest "Continue on current work xxxx."
